-- ============================================================================
--  BOOTSTRAP · the principal's account
--  Run in: Supabase dashboard → SQL Editor, on project `sse_portal`
--  Requires: migrations 001 and 002 already applied
--
--  Safe to run more than once.
-- ============================================================================
--
--  WHY THIS IS A MANUAL STEP
--
--  Migration 001 locked down `app_users`: only a super_admin may write it. The
--  first super_admin therefore cannot be created by the app — there is nobody
--  to authorise it. This is the chicken-and-egg noted in 001 §B, and the SQL
--  Editor is the way out, because it runs as `postgres` and bypasses RLS.
--
--  Do this ONCE. After it, the principal manages every other account from the
--  admin app.
-- ============================================================================


-- ----------------------------------------------------------------------------
--  STEP 1 — create the login account (dashboard UI, not SQL)
-- ----------------------------------------------------------------------------
--
--  Supabase dashboard → Authentication → Users → "Add user" → "Create new user"
--
--      Email     : principal@sunrise.edu.pk
--      Password  : (choose one — you will type it into the app)
--      ☑ Auto Confirm User      ← tick this, or login fails on an
--                                 unconfirmed-email error
--
--  Passwords must be hashed by Supabase Auth, which is why this cannot be
--  done in SQL. Everything below IS SQL.
--
--  Use a real password even for a prototype. This account can read every
--  student's marks, fees and guardian phone numbers.
-- ----------------------------------------------------------------------------


-- ----------------------------------------------------------------------------
--  STEP 2 — everything below: paste and Run
-- ----------------------------------------------------------------------------

BEGIN;

--  Reference rows the app's data hangs off. The ids are the deterministic
--  UUIDv5 values the local seeder produces (see tool/print_demo_ids.dart), so
--  the desktop and the server agree on which school this is.
INSERT INTO schools (id, name, address, phone, updated_at)
VALUES (
    'e05fe3c2-de30-513c-9fbb-125aefaa707a',
    'Sunrise School of Excellence',
    'Model Town, Lahore',
    '042-35880000',
    now()
)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, updated_at = now();

INSERT INTO academic_years
    (id, school_id, name, start_date, end_date, is_current, updated_at)
VALUES (
    '497e12ee-ade7-534b-a1ef-29298e30b3bb',
    'e05fe3c2-de30-513c-9fbb-125aefaa707a',
    '2026-2027', '2026-04-01', '2027-03-31', true, now()
)
ON CONFLICT (id) DO UPDATE SET is_current = true, updated_at = now();


--  The account you just created in Step 1, promoted to super_admin.
--
--  Looked up by email rather than by pasting a UUID — auth.users.id is
--  generated by Supabase and copying it by hand is exactly the sort of step
--  that gets done wrong at 2am.
--
--  app_users.id MUST equal auth.users.id: that equality is what makes
--  current_role_name() work, since it resolves auth.uid() against this table.
INSERT INTO app_users (id, school_id, role, email, full_name, is_active, updated_at)
SELECT
    u.id,
    'e05fe3c2-de30-513c-9fbb-125aefaa707a',
    'super_admin',
    u.email,
    'Principal',
    true,
    now()
FROM auth.users u
WHERE u.email = 'principal@sunrise.edu.pk'
ON CONFLICT (id) DO UPDATE
    SET role = 'super_admin', is_active = true, updated_at = now();


--  The seeded "Principal" that historical demo rows point at.
--
--  Every seeded attendance row carries marked_by = this id, and
--  attendance.marked_by is NOT NULL REFERENCES app_users(id). Without this row
--  the first push of back-dated attendance fails on a foreign key, which is a
--  confusing way to discover the problem mid-demo.
--
--  It is a data row only — nothing ever logs in as it, so it has no
--  auth.users entry and cannot be signed into.
INSERT INTO app_users (id, school_id, role, full_name, is_active, updated_at)
VALUES (
    'fcbad286-6a85-5964-ab97-a79282ee21c7',
    'e05fe3c2-de30-513c-9fbb-125aefaa707a',
    'super_admin',
    'Principal (seed)',
    true,
    now()
)
ON CONFLICT (id) DO UPDATE SET is_active = true, updated_at = now();

COMMIT;


-- ============================================================================
--  VERIFY — expect exactly 2 rows, and `linked` true on the login account
-- ============================================================================
--
--   SELECT a.full_name,
--          a.role,
--          a.email,
--          (u.id IS NOT NULL) AS linked_to_auth
--   FROM app_users a
--   LEFT JOIN auth.users u ON u.id = a.id
--   ORDER BY a.full_name;
--
--  If `linked_to_auth` is false on the login account, Step 1 did not run or
--  the email does not match. The account will not be able to sign in.
-- ============================================================================
